import Head from "next/head";
import { Inter } from "next/font/google";
import HomePage from "@/components/Page/HomePage/HomePage";

const inter = Inter({ subsets: ["latin"] });
import { Toaster } from 'react-hot-toast';
export default function Home() {
  return (
    <>
      <Head>
        <title>Email Verifier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${inter.className}`}>
        <HomePage />
        <Toaster />
      </main>
    </>
  );
}
