import React from "react";
import { Typography, Space } from "antd";
import MainLayout from "@/components/layouts/MainLayout";

const AboutPage = () => {
  return (
    <MainLayout>
      <div
        style={{
          width: "100%",
          height: "100vh",
          backgroundColor: "white",
          borderRadius: "16px",
          padding: "24px",
          boxShadow: "0 2px 10px rgba(0, 0, 0, 0.1)",
        }}
      >
        <Typography.Title level={2}>About the Email Verifier</Typography.Title>
        <Typography.Paragraph>
          The Email Verifier is a web application designed to help users verify
          the validity of email addresses efficiently. Whether you have a list
          of emails or need to check individual addresses, our tool offers a
          simple and intuitive interface to meet your needs.
        </Typography.Paragraph>

        <Typography.Title level={3}>Key Features</Typography.Title>
        <Space direction="vertical">
          <Typography.Paragraph>
            <strong>1. Bulk Email Verification:</strong> Upload an Excel file
            containing a list of email addresses to quickly verify their
            validity.
          </Typography.Paragraph>
          <Typography.Paragraph>
            <strong>2. Column Selection:</strong> Specify which column of the
            Excel sheet contains the email addresses for verification.
          </Typography.Paragraph>
          <Typography.Paragraph>
            <strong>3. Invalid Email Reporting:</strong> View a list of invalid
            emails detected during the verification process.
          </Typography.Paragraph>
          <Typography.Paragraph>
            <strong>4. Easy Download:</strong> Remove invalid emails and
            download the validated list for further use.
          </Typography.Paragraph>
        </Space>

        <Typography.Title level={3}>How to Use</Typography.Title>
        <Space direction="vertical">
          <Typography.Paragraph>
            1. Enter the column letter that contains your email addresses (e.g.,
            A, B).
          </Typography.Paragraph>
          <Typography.Paragraph>
            2. Upload your Excel file containing the emails.
          </Typography.Paragraph>
          <Typography.Paragraph>
            3. Review the list of invalid emails generated by the verifier.
          </Typography.Paragraph>
          <Typography.Paragraph>
            4. Remove invalid emails and download the validated list if
            desired.
          </Typography.Paragraph>
        </Space>

        <Typography.Title level={3}>Contact</Typography.Title>
        <Typography.Paragraph>
          For any questions or feedback, feel free to reach out to me at
          <a href="mailto:lambeobn@gmail.com"> lambeobn@gmail.com</a>.
        </Typography.Paragraph>
      </div>
    </MainLayout>
  );
};

export default AboutPage;
